services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
    networks:
      todo-list-development:
    depends_on:
      php-fpm:
        condition: service_started

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www
    networks:
      - todo-list-development
    depends_on:
      mysql:
        condition: service_started

  workspace:
    build:
      context: .
      dockerfile: ./docker/development/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    ports:
      - '${VITE_PORT:-5173}:5173'
    tty: true
    stdin_open: true
    volumes:
      - ./:/var/www
    networks:
      - todo-list-development

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-app}
      - MYSQL_USER=${MYSQL_USERNAME:-laravel}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-secret_root}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql-data-development:/var/lib/mysql
    networks:
      - todo-list-development

  redis:
    image: redis:alpine
    networks:
      - todo-list-development

networks:
  todo-list-development:

volumes:
  mysql-data-development:
