services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - todo-list-storage-production:/var/www/storage:ro
      - todo-list-public-assets:/var/www/public/build:ro
    networks:
      - todo-list-production
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      php-fpm:
        condition: service_healthy

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - todo-list-storage-production:/var/www/storage
      - todo-list-public-assets:/var/www/public/build
    networks:
      - todo-list-production
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "php-fpm-healthcheck || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-app}
      - MYSQL_USER=${MYSQL_USERNAME:-laravel}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-secret_root}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql-data-production:/var/lib/mysql
    networks:
      - todo-list-production
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - todo-list-production
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  todo-list-production:

volumes:
  todo-list-storage-production:
  todo-list-public-assets:
  mysql-data-production:
